api:
  type: chat
  streaming: true
  headers: null
  slo_unit: null
  slo_tpot_header: null
  slo_ttft_header: null
  response_format: null
  session_id_header_key: null
data:
  type: shareGPT
  path: configs/ShareGPT_V3_unfiltered_cleaned_split.json
  corpus_file_path: null
  input_distribution: null
  output_distribution: null
  shared_prefix: null
  multimodal: null
  trace: null
  otel_trace_replay: null
  weka_trace_replay: null
  conversation_replay: null
  visionarena: null
load:
  type: constant
  interval: 1.0
  stages:
  - rate: 5.0
    duration: 20
    num_requests: null
    concurrency_level: null
  - rate: 15.0
    duration: 45
    num_requests: null
    concurrency_level: null
  - rate: 25.0
    duration: 89          # Updated from 45 to 89 to hit 3,000 total requests
    num_requests: null
    concurrency_level: null
  sweep: null
  worker_max_concurrency: 100
  worker_max_tcp_connections: 2500
  trace: null
  circuit_breakers: []
  request_timeout: null
  lora_traffic_split: null
  base_seed: 1782978773116
metrics: null
report:
  request_lifecycle:
    summary: true
    per_stage: true
    per_request: true
    per_adapter: true
    per_adapter_stage: false
    percentiles:
    - 0.1
    - 1.0
    - 5.0
    - 10.0
    - 25.0
    - 50.0
    - 75.0
    - 90.0
    - 95.0
    - 99.0
    - 99.9
  prometheus:
    summary: true
    per_stage: false
  session_lifecycle:
    summary: true
    per_stage: true
    per_session: false
  goodput: null
storage:
  local_storage:
    path: reports_vertex_ai
    report_file_prefix: vertex_ai_gemini_3_flash_preview_
  google_cloud_storage: null
  simple_storage_service: null
server:
  type: vllm
  model_name: google/gemini-3-flash-preview
  base_url: http://127.0.0.1:8000/vertexai
  ignore_eos: false
  api_key: "$AUTH_TOKEN"
  cert_path: null
  key_path: null
tokenizer:
  pretrained_model_name_or_path: ./tokenizers/gemma-4-31B-it
  trust_remote_code: null
  token: null
circuit_breakers: null
